//
// Created by Saman on 29.08.23.
//

#ifndef DOUGHNUT_PREPROCESSOR_H
#define DOUGHNUT_PREPROCESSOR_H

#define GLM_FORCE_RADIANS
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#define GLM_FORCE_LEFT_HANDED
#define GLM_FORCE_SWIZZLE
//#define GLM_FORCE_MESSAGES

#define GLFW_INCLUDE_VULKAN

#endif //DOUGHNUT_PREPROCESSOR_H
